document.writeln("<ul>");
document.writeln("	<li class=\'person active\'>");
document.writeln("		<a href=\'index.html\'>个人中心</a>");
document.writeln("	</li>");
document.writeln("	<li class=\'person\'>");
document.writeln("		<a href=\'#\'>个人资料</a>");
document.writeln("		<ul>");
document.writeln("			<li> <a href=\'information.html\'>个人信息</a></li>");
document.writeln("			<li> <a href=\'safety.html\'>安全设置</a></li>");
document.writeln("			<li> <a href=\'address.html\'>收货地址</a></li>");
document.writeln("		</ul>");
document.writeln("	</li>");
document.writeln("	<li class=\'person\'>");
document.writeln("		<a href=\'#\'>我的交易</a>");
document.writeln("		<ul>");
document.writeln("			<li><a href=\'order.html\'>订单管理</a></li>");
document.writeln("			<li> <a href=\'comment.html\'>评价管理</a></li>");
document.writeln("		</ul>");
document.writeln("	</li>");
document.writeln("</ul>");